/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package erss.hwk3.ys319.qs33;


public class App {
    public static void main(String[] args) {
        Server server = new Server();
        server.recvRequest();
        
    }
}
