version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  
  # init:
  #   build: ./erss-hwk3-ys319-qs33
  #   command: ./gradlew installDist
  #   depends_on:
  #     - db

  sys:
    build: ./
    user: root
    command: bash -c "./gradlew installDist && ./build/install/erss-hwk3-ys319-qs33/bin/erss-hwk3-ys319-qs33"
    volumes:
      - "./:/app"
    depends_on:
      - db
    ports:
      - "12345:12345"

  